name: Build and no test and publish

on:
#  pull_request:
 push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Debug --no-restore
    
    - name: Test
      run: dotnet test -c Debug --no-build --verbosity normal --filter "Category!=LongRunning"

    # - name: Log into gitea Hub
    #   uses: docker/login-action@v3
    #   with:
    #     registry: 192.168.2.66:3000
    #     http: true
    #     insecure: true
    #     username: ${{ secrets.USER_NAME }}
    #     password: ${{ secrets.USER_PASSWORD }}

    # - name: Push the image to Gitea Hub
    #   run: docker push http://192.168.2.66:3000/sanjaypais/webapidapper

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: gitea.ref == 'refs/heads/master'
    steps:
      - uses: https://github.com/actions/checkout@v4
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          registry: 192.168.2.66:3000
          http: true
          insecure: true
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
#          config-inline: |
#            [registry."192.168.2.66:3000"]
#              http = true
#              insecure = true            
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true