DROP TABLE IF EXISTS "EntityRoleAttributes";
DROP TABLE IF EXISTS "EntityAttributes";

DROP TABLE IF EXISTS "EntityRoleActions";
DROP TABLE IF EXISTS "EntityActions";


DROP TABLE IF EXISTS "EntityRoles";
DROP TABLE IF EXISTS "Entities";

DROP TABLE IF EXISTS "Modules";

DROP TABLE IF EXISTS "GroupRoles";
DROP TABLE IF EXISTS "UserRoles";
DROP TABLE IF EXISTS "UserGroups";

DROP TABLE IF EXISTS "Groups";
DROP TABLE IF EXISTS "Roles";
DROP TABLE IF EXISTS "Users";

DROP TABLE IF EXISTS "Clients";
